{% set name = "spyder-unittest" %}
{% set version = "0.1.1" %}
{% set hash_type = "sha256" %}
{% set hash = "c0f19c10eb95281114e6c419c1f464a481cd4ccaeee3be7aea173e077e2b1567" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - lxml
    - nose
    - pytest
    - python
    - spyder >=3

test:
  imports:
    - spyder_unittest

about:
  home: https://github.com/spyder-ide/spyder-unittest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin that integrates popular unit test frameworks.
  description: |
    It allows you to run tests and view the results.
  dev_url: https://github.com/spyder-ide/spyder-unittest

extra:
  recipe-maintainers:
    - ccordoba12
    - jitseniesen
    - goanpeca
